[env]
monitor_speed = 115200

[esp32_base]
platform = espressif32
framework = arduino

[env:esp32dev]
extends = esp32_base
board = esp32dev

[env:esp32s2]
extends = esp32_base
board = esp32-s2-saola-1

[env:esp32s3]
extends = esp32_base
board = esp32-s3-devkitc-1

[env:esp32c3]
extends = esp32_base
board = esp32-c3-devkitm-1

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17
build_src_filter = -<*> +<MeasurementEngine.cpp>


